import { FEE_PERCENT } from "@tradejs/core/constants";
import {
  BacktestPriceMode,
  Direction,
  Interval,
  StrategyConfig,
} from "@tradejs/types";

export interface StructureZonesSideConfig {
  enable: boolean;
  direction: Direction;
  minRiskRatio: number;
}

export const config = {
  ENV: "BACKTEST",
  INTERVAL: "15" as Interval,
  MAKE_ORDERS: true,
  CLOSE_OPPOSITE_POSITIONS: false,
  BACKTEST_PRICE_MODE: "open" as const,
  AI_ENABLED: false,
  AI_MODE: "llm" as const,
  ML_ENABLED: false,
  ML_THRESHOLD: 0.1,
  MIN_AI_QUALITY: 3,
  FEE_PERCENT,
  MAX_LOSS_VALUE: 10,
  MA_FAST: 14,
  MA_MEDIUM: 49,
  MA_SLOW: 50,
  OBV_SMA: 10,
  ATR: 14,
  ATR_PCT_SHORT: 7,
  ATR_PCT_LONG: 30,
  BB: 20,
  BB_STD: 2,
  MACD_FAST: 12,
  MACD_SLOW: 26,
  MACD_SIGNAL: 9,
  STRUCTURE_ZONES_PIVOT_LENGTH: 5,
  STRUCTURE_ZONES_ATR_LENGTH: 14,
  STRUCTURE_ZONES_MIN_SWING_ATR: 0.8,
  STRUCTURE_ZONES_ZONE_WIDTH_ATR: 0.5,
  STRUCTURE_ZONES_ACCEPT_BARS: 2,
  STRUCTURE_ZONES_REACTION_CLOSE_BEYOND_ZONE: true,
  STRUCTURE_ZONES_REQUIRE_REACTION_BODY: true,
  STRUCTURE_ZONES_REQUIRE_BIAS_ALIGNMENT: true,
  STRUCTURE_ZONES_MIN_REACTION_DISTANCE_ATR: 0.1,
  STRUCTURE_ZONES_MIN_REACTION_DISTANCE_ATR_LONG: 0.75,
  STRUCTURE_ZONES_MIN_REACTION_DISTANCE_ATR_SHORT: 0.5,
  STRUCTURE_ZONES_MIN_ZONE_AGE_BARS: 0,
  STRUCTURE_ZONES_MAX_ZONE_AGE_BARS: 0,
  STRUCTURE_ZONES_MIN_TOUCH_ORDINAL: 1,
  STRUCTURE_ZONES_MAX_TOUCH_ORDINAL: 0,
  STRUCTURE_ZONES_PENDING_CONFIRMATION_MAX_BARS: 0,
  STRUCTURE_ZONES_MAX_ATR_PCT_RANK100: 50,
  STRUCTURE_ZONES_MIN_REACTION_CLOSE_DISTANCE_PCT: 0,
  STRUCTURE_ZONES_MIN_REACTION_CLOSE_DISTANCE_PCT_LONG: 0.75,
  STRUCTURE_ZONES_MIN_REACTION_CLOSE_DISTANCE_PCT_SHORT: 0,
  STRUCTURE_ZONES_MIN_TREND_PERSISTENCE: 0,
  STRUCTURE_ZONES_MIN_TREND_PERSISTENCE_LONG: 0,
  STRUCTURE_ZONES_MIN_TREND_PERSISTENCE_SHORT: 0.5,
  STRUCTURE_ZONES_TRADE_TRANSITION_BREAKOUTS: true,
  STRUCTURE_ZONES_STOP_ZONE_BUFFER_MULT: 0.2,
  STRUCTURE_ZONES_STOP_BUFFER_PCT: 0.03,
  STRUCTURE_ZONES_TARGET_R_MULT: 2,
  STRUCTURE_ZONES_TARGET_R_MULT_LONG: 0.8,
  STRUCTURE_ZONES_TARGET_R_MULT_SHORT: 1.2,
  STRUCTURE_ZONES_COOLDOWN_HOURS: 72,
  STRUCTURE_ZONES_EXIT_ON_OPPOSITE_SIGNAL: true,
  STRUCTURE_ZONES_MAX_FIGURE_POINTS: 180,
  LONG: {
    enable: true,
    direction: "LONG",
    minRiskRatio: 0.7,
  },
  SHORT: {
    enable: true,
    direction: "SHORT",
    minRiskRatio: 0.7,
  },
} as const;

export type StructureZonesConfig = StrategyConfig &
  Omit<typeof config, "BACKTEST_PRICE_MODE" | "LONG" | "SHORT"> & {
    BACKTEST_PRICE_MODE: BacktestPriceMode;
    LONG: StructureZonesSideConfig;
    SHORT: StructureZonesSideConfig;
  };
